### ISSUE TITLE
Exploration Task on Tech Stack

### ISSUE THREAD

**Issue by dabby04** [dabby04/TheLearningLayers#10]
We need to identify and explore what tech stack we would like to use for our project. Each team member would need to check this tech stack might benefit us in the long run such as why we decide on this programming language, what libraries or dependencies are available and how easy it would be for team members to identify and test with the code. We would like to have this completed by end of next week.

**Comment by atharvaj0gtap** [comment]
We could try using JavaScript for both frontend and backend development. JavaScript is one of the most popular programming languages with a vast ecosystem of libraries and frameworks. It can be used for both frontend (with frameworks like React) and backend (with Node.js). Or we could also go with Python which is easier to implement and provides us with several libraries. Let me know what you guys think.

**Comment by dabby04** [comment]
After discussing as a group, we decided to use the Python tech stack.
