### ISSUE TITLE
Add to the Figma design

### ISSUE THREAD

**Issue by dabby04** [dabby04/TheLearningLayers#2]
Create a high-fidelity prototype on Figma to visualise and validate the user interface and interactions for this project. By the end of our scrum meeting, we should collaborate and provide a detailed and polished prototype, incorporating realistic design elements and interactions. This prototype will serve as a foundation for user testing and visualisation of the final product and ensuring alignment with project goals and user expectations.

**Comment by dabby04** [comment]
I have made some changes to the figma design which has the requirements for students and teachers. I am working on adding the visual aspect of the admin page

**Comment by abstractafua** [comment]
I have added a create account page to the figma

**Comment by dabby04** [comment]
Figma has been updated with recent changes
