### ISSUE TITLE
Need to finish coding welcome and login page 

### ISSUE THREAD

**Issue by KarimKhalil33** [dabby04/TheLearningLayers#22]
Prioritize the development of the welcome and login pages by the upcoming deadline. This task involves finalizing the frontend design, ensuring backend integration for user authentication, and testing for both functionality and user experience. Achieving this milestone will mark a significant step forward in providing a seamless entry point for users, enhancing overall engagement and security

**Comment by pithegreat** [comment]
This task has been completed on the frontend
