### ISSUE TITLE
Retrieving data from database to studentPage

### ISSUE THREAD

**Issue by atharvaj0gtap** [dabby04/TheLearningLayers#23]
Need to figure out how to retrieve data from the mongoDB database and display it on the studentPage. Tried working on it today, my code has been saved to backend_v2 branch - it doesn't show errors but does not display the courses either. 
Feel free to check it out.

**Comment by dabby04** [comment]
Issue has been solved and course titles now pull directly from the database. However, we need to determine how to get the status of students enrolled courses.
@atharvaj0gtap @abstractafua
