### ISSUE TITLE
Make default value TBD for course instructor 

### ISSUE THREAD

**Issue by abstractafua** [dabby04/TheLearningLayers#49]
Set a default value ('TBA') for the instructor field in the database when a course is created without an assigned instructor.
Measurable: Ensure that the default value ('TBA') is automatically inserted into the instructor field whenever a new course is added to the database without specifying an instructor. Implement a database trigger or validation rule that assigns the default value ('TBA') to the instructor field upon course creation if no instructor is specified. This change will ensure that all courses in the database have a consistent value for the instructor field, improving data integrity and usability. Complete the implementation of the default value functionality for the instructor field within two weeks to coincide with the next sprint cycle.

**Comment by atharvaj0gtap** [comment]
The schema validation is only intend to enforce/validate a schema definition and not populate values.

The server does not have an ability to set default values and we recommend users to set it in their data access application layer or use ODM’s to set those values on the application side.

If you use Atlas you can consider having a trigger on the collection to update every inserted document with a specific filed value.

----- I found this post online, we're gonna need to figure it out

**Comment by atharvaj0gtap** [comment]
Solved the issue causing the problem by including a validation that checks if teacher field is empty and if it is then it assigns the teacher value to be "TBD". This was done in the backend_v2 branch
