### ISSUE TITLE
Populate MongoDB Database

### ISSUE THREAD

**Issue by abstractafua** [dabby04/TheLearningLayers#51]
Populate the MongoDB database with sample data relevant to the course collection. Insert at least 10 courses into course collection of the MongoDB database, ensuring that the data accurately represents the typical usage scenarios of the application.
Use scripts or tools to generate sample data or import data from external sources into the MongoDB database, ensuring that the data structure aligns with the course.js schema in the models folder. Populating the MongoDB database with relevant sample data enables us to validate the application's functionality, performance, and scalability in a realistic environment. Complete this issue before the start of the next sprint phase.

**Comment by dabby04** [comment]
I have added 5 courses which were used for testing, I added them through the createCourse page  and retrieved the data for testing.

**Comment by abstractafua** [comment]
I've populated the database with courses from the ubc academic calendar. Including course code titles and descriptions with TBA instructors
