### ISSUE TITLE
Generating UML Class diagram model 

### ISSUE THREAD

**Issue by abstractafua** [dabby04/TheLearningLayers#6]
By Wednesday, February 13th, @dabby04 and @KarimKhalil33  will collaboratively create a detailed UML diagram for our E-learning platform. The diagram will specifically illustrate functions and relationships among users, students, teachers, and admins. The finalized diagram will be reviewed and committed to the 'Requirements' folder.

**Comment by dabby04** [comment]
The UML Diagram has been added to the Requirements folder.
