### ISSUE TITLE
Create session for current user

### ISSUE THREAD

**Issue by atharvaj0gtap** [dabby04/TheLearningLayers#92]
We need to set the current state of the user who logs in/ set the session for that particular user, ie. it could be admin/teacher/student and we need to display info specific to that user. Eg: the courses that specific student is enrolled in etc. 

This is a major step to move forward for all the functionality and needs to be done ASAP

**Comment by dabby04** [comment]
I have worked on this and added the authentication Id to the login page. My changes are pushed on branch loginState. However, there are extra things to be done to make this work fully:
-  You might need to add a setState collection variable to App.js which checks the collection name and allows respective users to go to certain places of the website
-  You need to update each component to include this
<Route
          path="/dashboard"
          element={<Dashboard authenticationId={authenticationId} />}
        /> (*just an example*)

**Comment by dabby04** [comment]
I have finished the set state variable and updated this in my branch. I have created a pull request to the main. Please accept.
