### ISSUE TITLE
Create Assignment stores Assignment in database

### ISSUE THREAD

**Issue by dabby04** [dabby04/TheLearningLayers#98]
When the teacher creates an assignment, it should store the assignment in the database, along with the teacher id and courseId. This way, we can see the teacher who posted the assignment and what course it belonged to. This might need the setState variable of when teacher is logged in. This should be completed before next scrum meeting.

**Comment by atharvaj0gtap** [comment]
The assignment schema has been created to store the assignments on the database, just figuring out how to store files on the MongoDB database.

**Comment by atharvaj0gtap** [comment]
Wrote code to store assignment into database using multer file storage middleware, updated teacherAssignments.js and routes.js.
